DROP TABLE IF EXISTS `db_test_two_b`;
CREATE TABLE `db_test_two_b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `col0` varchar(255) NOT NULL DEFAULT '',
  `col1` varchar(255) NOT NULL DEFAULT '',
  `col2` varchar(255) NOT NULL DEFAULT '',
  `col3` varchar(255) NOT NULL DEFAULT '',
  `col4` varchar(255) NOT NULL DEFAULT '',
  `col5` varchar(255) NOT NULL DEFAULT '',
  `col6` varchar(255) NOT NULL DEFAULT '',
  `col7` varchar(255) NOT NULL DEFAULT '',
  `col8` varchar(255) NOT NULL DEFAULT '',
  `col9` varchar(255) NOT NULL DEFAULT '',
  `col10` varchar(255) NOT NULL DEFAULT '',
  `col11` varchar(255) NOT NULL DEFAULT '',
  `col12` varchar(255) NOT NULL DEFAULT '',
  `col13` varchar(255) NOT NULL DEFAULT '',
  `col14` varchar(255) NOT NULL DEFAULT '',
  `col15` varchar(255) NOT NULL DEFAULT '',
  `col16` varchar(255) NOT NULL DEFAULT '',
  `col17` varchar(255) NOT NULL DEFAULT '',
  `col18` varchar(255) NOT NULL DEFAULT '',
  `col19` varchar(255) NOT NULL DEFAULT '',
  `col20` varchar(255) NOT NULL DEFAULT '',
  `col21` varchar(255) NOT NULL DEFAULT '',
  `col22` varchar(255) NOT NULL DEFAULT '',
  `col23` varchar(255) NOT NULL DEFAULT '',
  `col24` varchar(255) NOT NULL DEFAULT '',
  `col25` varchar(255) NOT NULL DEFAULT '',
  `col26` varchar(255) NOT NULL DEFAULT '',
  `col27` varchar(255) NOT NULL DEFAULT '',
  `col28` varchar(255) NOT NULL DEFAULT '',
  `col29` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;
SET FOREIGN_KEY_CHECKS=1;
